version: "3.7"

services:
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  prefect-agent:
    image: prefecthq/prefect:latest
    depends_on:
      - kafka
    ports:
      - 4200:4200
    environment:
      PREFECT_API_URL: "http://localhost:4200"
      PREFECTCLOUD_API_KEY: "cli-44d4a3dd-d43e-47c6-adcb-393c4deb4576"
      KAFKA_BOOTSTRAP_SERVERS: "localhost:9092"
      KAFKA_BROKERS: "localhost:9092"
      FEED_INGESTOR: "default"
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
    volumes:
      - ./prefect-agent-secrets:/app/prefect/secrets
