version: "3.7"

services:

  postgres:
    command:
      - postgres
      - -c
      - max_connections=150
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${_DB}
    volumes:
        - postgres:/var/lib/postgresql/data
    healthcheck:
      interval: 10s
      retries: 60
      start_period: 2s
      test: pg_isready -q -d $${_DB} -U $${DB_USER} | grep "accepting connections" || exit 1
      timeout: 2s
    image: postgres:14
    restart: always
      
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    ports:
      - "2181:2181"

  kafka:
    image: confluentinc/cp-kafka:latest
    depends_on:
      - zookeeper
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://172.18.0.5:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
    ports:
      - "9092:9092"

  orion:
    restart: always
    build: .

    command: prefect orion start
    ports:
      - 4200:4200
    depends_on:
      postgres:
        condition: service_started
    volumes:
      - prefect_data:/root/.prefect
      - prefect_flows:/flows
    environment:
      PREFECT_ORION_API_HOST: 0.0.0.0
      PREFECT_ORION_DATABASE_CONNECTION_URL: postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@postgres:5432/${_DB}
      PREFECT_ORION_ANALYTICS_ENABLED: "false"
      PREFECT_LOGGING_SERVER_LEVEL: WARNING
      PREFECT_API_URL: ${PREFECT_API_URL}

  rss:
    build: .
    command: python3 /usr/app/rss_sync.py
    depends_on:
      kafka:
        condition: service_started
      orion:
        condition: service_started

    volumes:
      - ./app:/usr/app:ro
      - sqlite_data:/data/${_DB}.db

    environment:
      PREFECT_API_URL: http://172.18.0.4:4200/api/
      PREFECTCLOUD_API_KEY: "cli-44d4a3dd-d43e-47c6-adcb-393c4deb4576"
      KAFKA_BOOTSTRAP_SERVERS: "172.18.0.5:9092"
      KAFKA_BROKERS: "localhost:9092"
      FEED_INGESTOR: "default"
      QUEUE: "RSS_FEED_SYNC"
      RSS_FEED_URL: "https://news.google.com/rss"
      KAFKA_LOG4J_LOGGERS: "kafka.controller=INFO,kafka.producer.async.DefaultEventHandler=INFO,state.change.logger=INFO"
      DB_CONNECT: postgresql://${DB_USER}:${DB_PASSWORD}@postgres:5432/${_DB} #sqlite:///data/${_DB}.db
      # ALTERNATE_DB_CONNECT: postgresql+asyncpg://${DB_USER}:${DB_PASSWORD}@postgres:5432/${_DB}
volumes:
  postgres:
  sqlite_data:
  prefect_data:
  prefect_flows: